using Kipu.API.Document.Application.Services;
using Kipu.API.Document.Domain.Model.Commands;
using Kipu.API.Document.Domain.Model.ValueObjects;
using Kipu.API.Document.Domain.Repositories;
using Kipu.API.Shared.Domain.Repositories;

namespace Kipu.API.Document.Application.Internal.CommandServices;

public class DocumentCommandService : IDocumentCommandService
{
    private readonly IDocumentRepository _documentRepository;
    private readonly IUnitOfWork _unitOfWork;

    public DocumentCommandService(IDocumentRepository documentRepository, IUnitOfWork unitOfWork)
    {
        _documentRepository = documentRepository;
        _unitOfWork = unitOfWork;
    }

    public async Task<Domain.Model.Aggregates.Document?> Handle(CreateDocumentCommand command)
    {
        var document = new Domain.Model.Aggregates.Document(command.Type, command.Deadline, command.ProjectId);

        foreach (var participant in command.Participants)
        {
            document.AddParticipant(participant.TeamUserId, participant.FullName);
        }

        try
        {
            await _documentRepository.AddAsync(document);
            await _unitOfWork.CompleteAsync();
            return document;
        }
        catch (Exception e)
        {
            Console.WriteLine($"An error happened creating the document: {e.Message}");
            return null;
        }
    }

    public async Task<Domain.Model.Aggregates.Document?> Handle(SignDocumentAsParticipantCommand command)
    {
        var documentId = new DocumentId(command.DocumentId);
        var document = await _documentRepository.FindByIdAsync(documentId);

        if (document is null) return null;

        var participant = document.Participants.FirstOrDefault(p => p.TeamUserId == command.TeamUserId);
        
        if (participant is null)
            return null;

        participant.MarkAsSigned();

        bool allSigned = document.Participants.All(p => p.SignedAt != null);
        
        if (allSigned && !document.IsSigned)
        {
            string autogeneratedToken = $"SIGN-{Guid.NewGuid().ToString("N").ToUpper()}";
            
            document.SignDocument(autogeneratedToken);
        }

        try
        {
            _documentRepository.Update(document);
            await _unitOfWork.CompleteAsync();
            return document;
        }
        catch (Exception e)
        {
            Console.WriteLine($"An error happened signing the document: {e.Message}");
            return null;
        }
    }
}