// <auto-generated />
using System;
using Kipu.API.Shared.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kipu.API.Shared.Infrastructure.Persistence.EFC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617232353_FixExistingBudgetLineIdZero")]
    partial class FixExistingBudgetLineIdZero
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Kipu.API.Document.Domain.Model.Aggregates.Document", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deadline");

                    b.Property<string>("DigitalSignatureToken")
                        .HasColumnType("longtext")
                        .HasColumnName("digital_signature_token");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_signed");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("project_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("document", (string)null);
                });

            modelBuilder.Entity("Kipu.API.IAM.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Kipu.API.Logistics.Domain.Model.Aggregates.MaterialCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<int>("MeasureUnit")
                        .HasColumnType("int")
                        .HasColumnName("measure_unit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_material_catalogs");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_material_catalogs_name");

                    b.ToTable("material_catalogs");
                });

            modelBuilder.Entity("Kipu.API.Logistics.Domain.Model.Aggregates.MaterialCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_material_categories");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_material_categories_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_material_categories_name");

                    b.ToTable("material_categories");
                });

            modelBuilder.Entity("Kipu.API.Logistics.Domain.Model.Aggregates.MaterialInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CurrentStock")
                        .HasColumnType("int")
                        .HasColumnName("current_stock");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("location");

                    b.Property<int>("MaterialCatalogId")
                        .HasColumnType("int")
                        .HasColumnName("material_catalog_id");

                    b.Property<int>("MinimumStock")
                        .HasColumnType("int")
                        .HasColumnName("minimum_stock");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("p_k_material_inventories");

                    b.ToTable("material_inventories");
                });

            modelBuilder.Entity("Kipu.API.Logistics.Domain.Model.Aggregates.MaterialRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalNotes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("additional_notes");

                    b.Property<int?>("BudgetLineId")
                        .HasColumnType("int")
                        .HasColumnName("budget_line_id");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deadline");

                    b.Property<string>("DeliveryLocation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("delivery_location");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("purpose");

                    b.Property<int>("RequestPriority")
                        .HasColumnType("int")
                        .HasColumnName("request_priority");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("int")
                        .HasColumnName("request_status");

                    b.Property<int>("RequestedBy")
                        .HasColumnType("int")
                        .HasColumnName("requested_by");

                    b.HasKey("Id")
                        .HasName("p_k_material_requests");

                    b.HasIndex("RequestStatus")
                        .HasDatabaseName("i_x_material_requests_request_status");

                    b.ToTable("material_requests");
                });

            modelBuilder.Entity("Kipu.API.Logistics.Domain.Model.Aggregates.MaterialRequestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("MaterialCatalogId")
                        .HasColumnType("int")
                        .HasColumnName("material_catalog_id");

                    b.Property<int>("MaterialRequestId")
                        .HasColumnType("int")
                        .HasColumnName("material_request_id");

                    b.Property<int?>("MaterialRequestId1")
                        .HasColumnType("int")
                        .HasColumnName("material_request_id1");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("quantity");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("p_k_material_request_items");

                    b.HasIndex("MaterialRequestId")
                        .HasDatabaseName("i_x_material_request_items_material_request_id");

                    b.HasIndex("MaterialRequestId1")
                        .HasDatabaseName("i_x_material_request_items_material_request_id1");

                    b.ToTable("material_request_items");
                });

            modelBuilder.Entity("Kipu.API.Logistics.Domain.Model.Aggregates.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contact");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PaymentTerms")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("payment_terms");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("ruc");

                    b.Property<string>("SocialReason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("social_reason");

                    b.HasKey("Id")
                        .HasName("p_k_suppliers");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_suppliers_email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_suppliers_is_active");

                    b.HasIndex("Ruc")
                        .IsUnique()
                        .HasDatabaseName("i_x_suppliers_ruc");

                    b.ToTable("suppliers");
                });

            modelBuilder.Entity("Kipu.API.Logistics.Domain.Model.Aggregates.SupplierOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("MaterialCatalogId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("p_k_supplier_offers");

                    b.HasIndex("SupplierId", "MaterialCatalogId")
                        .IsUnique();

                    b.ToTable("supplier_offers");
                });

            modelBuilder.Entity("Kipu.API.Projects.Domain.Model.Aggregates.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<double>("Budget")
                        .HasColumnType("double")
                        .HasColumnName("budget");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("image");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("location");

                    b.Property<int>("Members")
                        .HasColumnType("int")
                        .HasColumnName("members");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("Pending")
                        .HasColumnType("int")
                        .HasColumnName("pending");

                    b.Property<int>("Progress")
                        .HasColumnType("int")
                        .HasColumnName("progress");

                    b.Property<int>("Rnc")
                        .HasColumnType("int")
                        .HasColumnName("rnc");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("StatusJustification")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status_justification");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_projects");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_projects_name");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("Kipu.API.Projects.Domain.Model.Aggregates.ProjectItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_project_items");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("i_x_project_items_project_id");

                    b.ToTable("project_items");
                });

            modelBuilder.Entity("Kipu.API.Team.TeamUser.domain.model.Aggregates.TeamUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("project_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("team_user", (string)null);
                });

            modelBuilder.Entity("Kipu.API.Team.TeamWorker.Domain.Model.Aggregates.TeamWorker", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("dni");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isActive");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("project_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("team_worker", (string)null);
                });

            modelBuilder.Entity("Kipu.API.Document.Domain.Model.Aggregates.Document", b =>
                {
                    b.OwnsMany("Kipu.API.Document.Domain.Model.Aggregates.DocumentParticipant", "Participants", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("full_name");

                            b1.Property<DateTimeOffset?>("SignedAt")
                                .HasColumnType("datetime")
                                .HasColumnName("signed_at");

                            b1.Property<string>("TeamUserId")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("id_team_user");

                            b1.Property<string>("id_document")
                                .HasColumnType("varchar(255)");

                            b1.HasKey("Id");

                            b1.HasIndex("id_document");

                            b1.ToTable("documentXteam_user", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("id_document");
                        });

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Kipu.API.Logistics.Domain.Model.Aggregates.MaterialRequestItem", b =>
                {
                    b.HasOne("Kipu.API.Logistics.Domain.Model.Aggregates.MaterialRequest", null)
                        .WithMany("Items")
                        .HasForeignKey("MaterialRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_material_request_items_material_requests_material_request_id");

                    b.HasOne("Kipu.API.Logistics.Domain.Model.Aggregates.MaterialRequest", "MaterialRequest")
                        .WithMany()
                        .HasForeignKey("MaterialRequestId1")
                        .HasConstraintName("f_k_material_request_items_material_requests_material_request_id1");

                    b.Navigation("MaterialRequest");
                });

            modelBuilder.Entity("Kipu.API.Projects.Domain.Model.Aggregates.ProjectItem", b =>
                {
                    b.HasOne("Kipu.API.Projects.Domain.Model.Aggregates.Project", "Project")
                        .WithMany("Items")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_project_items_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Kipu.API.Team.TeamUser.domain.model.Aggregates.TeamUser", b =>
                {
                    b.OwnsOne("Kipu.API.Team.TeamUser.domain.model.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<string>("TeamUserId")
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("email");

                            b1.HasKey("TeamUserId");

                            b1.ToTable("team_user");

                            b1.WithOwner()
                                .HasForeignKey("TeamUserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("Kipu.API.Team.TeamWorker.Domain.Model.Aggregates.TeamWorker", b =>
                {
                    b.OwnsMany("Kipu.API.Team.TeamWorker.Domain.Model.Aggregates.WorkerMachinery", "Machineries", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("id");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("fullName");

                            b1.Property<string>("MachineryId")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("id_machinery");

                            b1.Property<string>("id_team_worker")
                                .HasColumnType("varchar(255)");

                            b1.HasKey("Id");

                            b1.HasIndex("id_team_worker");

                            b1.ToTable("team_workerXmachinery", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("id_team_worker");
                        });

                    b.Navigation("Machineries");
                });

            modelBuilder.Entity("Kipu.API.Logistics.Domain.Model.Aggregates.MaterialRequest", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Kipu.API.Projects.Domain.Model.Aggregates.Project", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
